### ISSUE TITLE
PHP8.2, empty perfdata graphs

### ISSUE THREAD

**Issue by schnudd31do3** [ConSol/pnp#1]
Parameters:
Nagios 4.4.6-4, Nagvis 1.9.37 (latest from Github), php7.4. With pnp-version 0.6.42 perfdata is displayed correctly.

After upgrading to php8.2, there are only blank window shown without any graphs.

When hoovering over the perfdata icon:
![image](https://github.com/ConSol-Monitoring/pnp/assets/72391822/f160789e-2b3a-4cad-9f4e-f2207e2e43a9)
 
After clicking on the perfdata-icon:
![image](https://github.com/ConSol-Monitoring/pnp/assets/72391822/616a9cd1-c9cb-4961-a6a3-2dc09bdef396)

**Comment by datamuc** [comment]
Can you find something helpful in the apache error log or so?

**Comment by schnudd31do3** [comment]
Thanks for your hint. It was due to a temporary failed ldap login. I did not reboot after upgrading. So, all is working fine.
